server:
  port: ${SERVER_PORT:8888}

spring:
  application:
    name: configuration-server
  main:
    banner-mode: off
  cloud:
    config:
      server:
        default-label: main
        git:
          clone-on-start: true
          uri: ${GIT_URI:https://github.com/rafaelprudente/MEGSI-CONFIG-SERVER-DATA.git}
          #ignoreLocalSshSettings: true
          #hostKeyAlgorithm: ssh-ed25519
          #hostKey: AAAAC3NzaC1lZDI1NTE5AAAAIOMqqnkVzrm0SdG6UOoqKLsabgH5C9okWi0dh2l9GKJl
          #privateKey: ${SSH_KEY}

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    env:
      show-values: ALWAYS
    health:
      probes:
        enabled: true
  health:
    livenessState:
      enabled: true
    readinessState:
      enabled: true

logging:
  level:
    root: ${LOG_LEVEL:INFO}