server.port=${SERVER_PORT:8888}
spring.application.name=configuration-server

spring.main.banner-mode=off

spring.cloud.config.server.git.uri=${GIT_URI:https://github.com/rafaelprudente/MEGSI-CONFIG-SERVER-DATA.git}
spring.cloud.config.server.git.default-label=${GIT_BRANCH:main}

management.endpoint.health.probes.enabled=true
management.health.livenessState.enabled=true
management.health.readinessState.enabled=true

logging.level.root=${LOG_LEVEL:INFO}