server:
  port: ${SERVER_PORT:8888}

spring:
  application:
    name: configuration-server
  main:
    banner-mode: off
  cloud:
    config:
      server:
        git:
          clone-on-start: true
          default-label: main
          tryMasterBranch: false
          uri: ${GIT_URI:https://github.com/rafaelprudente/MEGSI-CONFIG-SERVER-DATA.git}

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    env:
      show-values: ALWAYS
    health:
      probes:
        enabled: true
  health:
    livenessState:
      enabled: true
    readinessState:
      enabled: true

logging:
  level:
    root: ${LOG_LEVEL:INFO}