replicaCount: 1

deployment:
  forceRedeploy: ""

image:
  repository: 192.168.56.101/configuration-server
  tag: latest
  pullPolicy: Always

service:
  type: ClusterIP
  port: 8888
  targetPort: 8888

resources:
  limits:
    cpu: "500m"
    memory: "1024Mi"
  requests:
    cpu: "100m"
    memory: "512Mi"

readinessProbe:
  path: /actuator/health/readiness
  port: 8888

livenessProbe:
  path: /actuator/health/liveness
  port: 8888