# ... Deploy YAML definition
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Release.Name }}
  template:
    metadata:
      annotations:
        rollme: "{{ .Values.deployment.forceRedeploy | default "none" }}"
      labels:
        app: {{ .Release.Name }}
    spec:
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 100
              podAffinityTerm:
                labelSelector:
                  matchLabels:
                    group: service-group-2
                topologyKey: "kubernetes.io/hostname"
      containers:
        - name: {{ .Release.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.service.targetPort }}
          env:
            - name: JAVA_TOOL_OPTIONS
              value: "-XX:+UseG1GC -XX:MaxRAMPercentage=70"
          readinessProbe:
            httpGet:
              port: {{ .Values.readinessProbe.port }}
              path: {{ .Values.readinessProbe.path }}
            initialDelaySeconds: 100
            timeoutSeconds: 1
            periodSeconds: 20
            successThreshold: 1
            failureThreshold: 8
          livenessProbe:
            httpGet:
              port: {{ .Values.livenessProbe.port }}
              path: {{ .Values.livenessProbe.path }}
            initialDelaySeconds: 90
            timeoutSeconds: 1
            periodSeconds: 20
            successThreshold: 1
            failureThreshold: 5
          resources:
            limits:
              cpu: {{ .Values.resources.limits.cpu }}
              memory: {{ .Values.resources.limits.memory }}
            requests:
              cpu: {{ .Values.resources.requests.cpu }}
              memory: {{ .Values.resources.requests.memory }}